# Generated by Django 2.2.1 on 2019-05-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
